version: '3'
services:
  springboot:
    build: ./springboot/
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8080:8080"
    links:
      - mysql:db
  mysql:
    build: ./mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
