version: '3'
services:
  mysql:
    build: ./mysql/
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: amt_project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  springboot:
    build: ./springboot/
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  
